# Generated by Django 5.1.3 on 2024-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/categories')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/products')),
                ('price', models.BigIntegerField(blank=True, default=0)),
                ('old_price', models.BigIntegerField(blank=True, default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='products.categories')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
